# Generated by Django 3.0.5 on 2020-04-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showTimesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
