# Generated by Django 3.0.5 on 2020-04-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showTimesApp', '0003_auto_20200421_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='showTimesApp.Category'),
        ),
    ]
